name: CI Pipeline (Layered DevSecOps)

on:
  push:
    branches: [ "dev", "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ===============================
      # SAST (always run)
      # ===============================
      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: |
          cppcheck \
            --enable=all \
            --inconclusive \
            --error-exitcode=1 \
            --std=c++17 \
            --language=c++ \
            --suppress=missingIncludeSystem \
            -i build \
            ./src

      # ===============================
      # Dev stage (dev branch only)
      # ===============================
      - name: Dev stage
        if: github.ref == 'refs/heads/dev'
        run: echo "Dev pipeline - SAST only"

      # ===============================
      # Build (main / PR / tag)
      # ===============================
      - name: Set up Docker Buildx
        if: github.ref != 'refs/heads/dev'
        uses: docker/setup-buildx-action@v4

      - name: Cache Docker layers
        if: github.ref != 'refs/heads/dev'
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image (internal)
        if: github.ref != 'refs/heads/dev'
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --load \
            -t edge-demo:${{ github.sha }} .

      - name: Move cache
        if: github.ref != 'refs/heads/dev'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # ===============================
      # Dependency scanning (SCA)
      # ===============================
      - name: Trivy FS scan
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      # ===============================
      # Image scanning
      # ===============================
      - name: Trivy image scan
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: edge-demo:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      # ===============================
      # Release (tag-driven only)
      # ===============================
      - name: Configure AWS credentials
        if: startsWith(github.ref, 'refs/tags/')
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: startsWith(github.ref, 'refs/tags/')
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image (release)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker buildx build \
            --load \
            -t edge-demo:${{ github.ref_name }} .

      - name: Tag image for ECR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag edge-demo:${{ github.ref_name }} \
          ${{ steps.login-ecr.outputs.registry }}/edge-demo:${{ github.ref_name }}

      - name: Push image to ECR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/edge-demo:${{ github.ref_name }}
