name: CI Build (Docker)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔥 开启 Buildx（支持 cache）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔥 Docker cache（核心加速）
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # 🔥 build + load（关键）
      - name: Build Docker image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --load \
            -t edge-demo .

      # 🔥 移动 cache（重要）
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # 🔥 SHA tag
      - name: Tag image with SHA
        run: docker tag edge-demo edge-demo:${{ github.sha }}


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t edge-demo .

      - name: Tag image for ECR
        run: |
          docker tag edge-demo ${{ steps.login-ecr.outputs.registry }}/edge-demo:${{ github.sha }}

      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/edge-demo:${{ github.sha }}
